licenses(["notice"])  # Apache 2.0

py_binary(
    name = "wikipedia_sourcelist_generator",
    srcs = ["wikipedia_sourcelist_generator.py"],
    srcs_version = "PY2AND3",
    visibility = ["//visibility:public"],
)
