package(default_visibility = ["//visibility:public"])

load("@io_bazel_rules_closure//closure:defs.bzl", "closure_js_proto_library")

closure_js_proto_library(
    name = "proto",
    srcs = ["feature_statistics.proto"],
)