package(default_visibility = ["//visibility:public"])

load("@io_bazel_rules_closure//closure:defs.bzl", "closure_js_proto_library")

licenses(["notice"])  # Apache 2.0

closure_js_proto_library(
    name = "proto",
    srcs = ["feature_statistics.proto"],
)